### ISSUE TITLE
Expired wrong date

### ISSUE THREAD

**Issue by InvokerFury** [Matty9191/ssl-cert-check#32] opened 2018-07-10 11:15 UTC
hy sir, thx for your script..
i got some problem.. when i cek with sslshopper.com the domain espay id will expire in 12 days 

![image](https://user-images.githubusercontent.com/24584431/42506769-0702c302-846d-11e8-83d2-1b09b42921db.png)

but if i check with ssl-chert script i got 88 days sir..
./ssl-cert-check -s espay.id -p 443          

Host                                            Status       Expires      Days
----------------------------------------------- ------------ ------------ ----
espay.id:443                                    Valid        Oct 6 2018   88 

could u help me sir? thx

**Comment by Matty9191** [comment] 2018-07-10 14:16
I'm not familiar with the website you mention. The data reported by ssl-cert-check appears to be correct. Here is the CN and validity information from the X509 certificate: 

        Validity
            Not Before: Jul  8 00:00:00 2018 GMT
            Not After : Oct  6 23:59:59 2018 GMT
        Subject: CN = espay.id

**Comment by InvokerFury** [comment] 2018-07-10 16:03
if i check from ssl-cert-check it mention correct expired date.. 
![image](https://user-images.githubusercontent.com/24584431/42522479-652cb6a4-8495-11e8-97f1-caa9c0a9d3b5.png)

but if i sent it to email when recipient multiple email, this domain expired..if just 1 recipient it correct 

![image](https://user-images.githubusercontent.com/24584431/42522156-a371b488-8494-11e8-89d5-265ddc2468a6.png)

**Comment by Matty9191** [comment] 2018-09-13 13:17
Are you still seeing this issue? If so, can you send me the domain so I can debug further?

**Comment by InvokerFury** [comment] 2018-09-13 17:40
hy Matty thanks for ur respon..
here matty https://scm.bankmandiri.co.id/.. please dont tell anyone about
this please

**Comment by Matty9191** [comment] 2018-09-13 18:06
You may want to delete your comment if you don't want anyone to know about your domain. I tested this on a Centos 7 machine and it works correctly in interactive and batch mode. What OS are you running?

**Comment by InvokerFury** [comment] 2018-09-14 09:38
its normal when i check it manual, but when i run it into cron it will say
expired.. in my email

**Comment by affinityv** [comment] 2018-10-20 20:55
The problem is due to the bug fixed in 3.31 -- you can adjust your script by changing one line as follows:

sed -i 's/s_client -h /s_client -help /' /usr/bin/ssl-cert-check

**Comment by Matty9191** [comment] 2019-02-11 15:08
Thanks for the feedback. The script is now using "-help".

**Closed by Matty9191** 2019-02-11 15:08 UTC
